export default [
  {
    title: "Rice chicken and spicies",
    sub_title: "spicy chicken red BBQ",
    colories: "105 calories",
    category: "makanan",
    price: "#14,000",
    image_path: "./menuimage1.png",
  },
  {
    title: "Amala with gbegiri",
    sub_title: "amala and ewedu",
    colories: "109 calories",
    category: "minuman",
    price: "#20,000",
    image_path: "./menuimage2.png",
  },
  {
    title: "Fufu and tuwo salad",
    sub_title: "spicy chicken red BBQ",
    colories: "116 calories",
    category: "makanan",
    price: "#12,000",
    image_path: "./menuimage3.png",
  },
  {
    title: "Ofansala ukwobi",
    sub_title: "ukwobi prepared",
    colories: "98 calories",
    category: "minuman",
    price: "#7,000",
    image_path: "./menuimage4.png",
  },
  {
    title: "Rice chicken and spicies",
    sub_title: "spicy chicken red BBQ",
    colories: "105 calories",
    category: "makanan",
    price: "#14,000",
    image_path: "./menuimage1.png",
  },
  {
    title: "Amala with gbegiri",
    sub_title: "amala and ewedu",
    colories: "109 calories",
    category: "minuman",
    price: "#20,000",
    image_path: "./menuimage2.png",
  },
  {
    title: "Fufu and tuwo salad",
    sub_title: "spicy chicken red BBQ",
    colories: "116 calories",
    category: "makanan",
    price: "#12,000",
    image_path: "./menuimage3.png",
  },
  {
    title: "Ofansala ukwobi",
    sub_title: "ukwobi prepared",
    colories: "98 calories",
    category: "minuman",
    price: "#7,000",
    image_path: "./menuimage4.png",
  },
  {
    title: "Rice chicken and spicies",
    sub_title: "spicy chicken red BBQ",
    colories: "105 calories",
    category: "makanan",
    price: "#14,000",
    image_path: "./menuimage1.png",
  },
  {
    title: "Amala with gbegiri",
    sub_title: "amala and ewedu",
    colories: "109 calories",
    category: "minuman",
    price: "#20,000",
    image_path: "./menuimage2.png",
  },
  {
    title: "Fufu and tuwo salad",
    sub_title: "spicy chicken red BBQ",
    colories: "116 calories",
    category: "makanan",
    price: "#12,000",
    image_path: "./menuimage3.png",
  },
  {
    title: "Ofansala ukwobi",
    sub_title: "ukwobi prepared",
    colories: "98 calories",
    category: "minuman",
    price: "#7,000",
    image_path: "./menuimage4.png",
  },
  {
    title: "Rice chicken and spicies",
    sub_title: "spicy chicken red BBQ",
    colories: "105 calories",
    category: "makanan",
    price: "#14,000",
    image_path: "./menuimage1.png",
  },
  {
    title: "Amala with gbegiri",
    sub_title: "amala and ewedu",
    colories: "109 calories",
    category: "minuman",
    price: "#20,000",
    image_path: "./menuimage2.png",
  },
  {
    title: "Fufu and tuwo salad",
    sub_title: "spicy chicken red BBQ",
    colories: "116 calories",
    category: "makanan",
    price: "#12,000",
    image_path: "./menuimage3.png",
  },
  {
    title: "Ofansala ukwobi",
    sub_title: "ukwobi prepared",
    colories: "98 calories",
    category: "minuman",
    price: "#7,000",
    image_path: "./menuimage4.png",
  },
  {
    title: "Rice chicken and spicies",
    sub_title: "spicy chicken red BBQ",
    colories: "105 calories",
    category: "makanan",
    price: "#14,000",
    image_path: "./menuimage1.png",
  },
  {
    title: "Amala with gbegiri",
    sub_title: "amala and ewedu",
    colories: "109 calories",
    category: "minuman",
    price: "#20,000",
    image_path: "./menuimage2.png",
  },
  {
    title: "Fufu and tuwo salad",
    sub_title: "spicy chicken red BBQ",
    colories: "116 calories",
    category: "makanan",
    price: "#12,000",
    image_path: "./menuimage3.png",
  },
  {
    title: "Ofansala ukwobi",
    sub_title: "ukwobi prepared",
    colories: "98 calories",
    category: "minuman",
    price: "#7,000",
    image_path: "./menuimage4.png",
  },
];
